version: '3'

x-uffizzi:
  ingress:
      service: ospos
      port: 80
  
services:
    ospos: 
        image: "${ OSPOS_IMAGE }"
        depends_on: 
          - mysql
        container_name: ospos
        environment:
          - CI_ENV=production
          - MYSQL_HOST_NAME=localhost
          - MYSQL_DATABASE=ospos
          - MYSQL_USERNAME=admin
          - MYSQL_PASSWORD=pointofsale
        command: ["/bin/wait-for-it.sh", "localhost:3306", "--", "sleep infinity"]
        ports:
          - "80:80"

    mysql:
        image: mariadb:10.5
        container_name: mysql
        restart: always
        ports:
          - "3306:3306" 
        environment:
          - MYSQL_ROOT_PASSWORD=pointofsale
          - MYSQL_DATABASE=ospos
          - MYSQL_USER=admin
          - MYSQL_PASSWORD=pointofsale